sudo: false
language: ruby
rvm:
  - 2.4.1
before_install:
  - curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
  - brew upgrade rbenv ruby-build
  - curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
  - gem install bundler -v 1.15.3
