sudo: false
language: ruby
rvm:
  - 2.4.1
before_install:
  - git branch
  - git fetch --unshallow
  - git fetch --all
  - git branch
  - git branch master origin/master
  - gem install bundler -v 1.15.3
