sudo: false
language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler -v 1.15.3
  # To have access to the whole repo
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --unshallow --tags
  # To no longer be in a detached HEAD state
  - git symbolic-ref --short HEAD || git checkout -b ${TRAVIS_BRANCH}-test $TRAVIS_BRANCH
