name: CI

on: [push]

env:
  ruby_version: "2.6.0"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.ruby_version }}
        bundler-cache: true

    - name: Run specs
      run: bundle exec rspec
