name: CI

on: [push]

env:
  ruby_version: 2.6.10

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx to be able to use caching
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx to be able to use caching
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        load: true
        tags: autowow
        cache-from: type=gha
        cache-to: type=gha

    - name: Run specs
      run: docker run --rm -i -v $(pwd):/app autowow bundle exec rspec

  require:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx to be able to use caching
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        load: true
        tags: autowow
        cache-from: type=gha
        cache-to: type=gha

    - name: Check if source can be required and is correctly required
      run: docker run --rm -i -v $(pwd):/app autowow bundle exec rake require
