name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx to be able to use caching
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: autowow
          cache-from: type=gha
          cache-to: type=gha

      - name: Run specs
        run: docker run --rm -it --entrypoint rspec -v $(pwd):/app autowow
