name: CI

on: [push]

env:
  ruby_version: "2.6.0"

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ env.ruby_version }}
    - name: Cache Ruby dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/autowow.gemspec') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Install Ruby dependencies
      run: |
        bundle config path vendor/bundle
        bundle install
    - name: Run specs
      run: bundle exec rspec
